version: "3.4"

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - db_data:/var/opt/mssql
      - ./run-script-db.sh:/usr/local/bin/entrypoint.sh
    entrypoint: /usr/local/bin/entrypoint.sh
    secrets:
      - db_password
  familybudget:
    image: familybudget
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:7134;http://+:5064
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/certificate.key
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5064:5064
      - 7134:7134
    depends_on:
      - sqldata
    entrypoint: /usr/local/bin/entrypoint.sh
    volumes:
      - ./run-script.sh:/usr/local/bin/entrypoint.sh
      - ./.certificates/https:/https:ro
    secrets:
      - jwt_secret
      - db_password
      - ssl_password

secrets:
  jwt_secret:
    file: ./.secretStorage/secrets/JWTSecret.txt
  db_password:
    file: ./.secretStorage/secrets/DbPassword.txt
  ssl_password:
    file: ./.secretStorage/secrets/SslPassword.txt

volumes:
  db_data:
