# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  familybudget:
    image: familybudget
    build:
      context: .
      dockerfile: FamilyBudget.Backend/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7134:7134
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
