# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - db_data:/var/opt/mssql
      - ./run-script-db.sh:/usr/local/bin/entrypoint.sh
    entrypoint: /usr/local/bin/entrypoint.sh
    secrets:
      - db_password
  familybudget:
    image: familybudget
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORT=http://+:5001
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - 5001:5001
    depends_on:
      - sqldata
    entrypoint: /usr/local/bin/entrypoint.sh
    volumes:
      - ./run-script.sh:/usr/local/bin/entrypoint.sh
    secrets:
      - jwt_secret
      - db_password

secrets:
  jwt_secret:
    file: ./.secretStorage/secrets/JWTSecret.txt
  db_password:
    file: ./.secretStorage/secrets/DbPassword.txt

volumes:
  db_data:
